import React from 'react'

// Mock for @heroicons/react
export const HomeIcon = () => React.createElement('div', { 'data-testid': 'home-icon' })
export const UserIcon = () => React.createElement('div', { 'data-testid': 'user-icon' })
export const CogIcon = () => React.createElement('div', { 'data-testid': 'cog-icon' })
export const ChartBarIcon = () => React.createElement('div', { 'data-testid': 'chart-bar-icon' })
export const ShieldExclamationIcon = () => React.createElement('div', { 'data-testid': 'shield-exclamation-icon' })
export const ChevronRightIcon = () => React.createElement('div', { 'data-testid': 'chevron-right-icon' })
export const PlusIcon = () => React.createElement('div', { 'data-testid': 'plus-icon' })
export const PencilIcon = () => React.createElement('div', { 'data-testid': 'pencil-icon' })
export const TrashIcon = () => React.createElement('div', { 'data-testid': 'trash-icon' })
export const EyeIcon = () => React.createElement('div', { 'data-testid': 'eye-icon' })
export const XMarkIcon = () => React.createElement('div', { 'data-testid': 'x-mark-icon' })
export const CheckIcon = () => React.createElement('div', { 'data-testid': 'check-icon' })
export const ExclamationTriangleIcon = () => React.createElement('div', { 'data-testid': 'exclamation-triangle-icon' })
export const InformationCircleIcon = () => React.createElement('div', { 'data-testid': 'information-circle-icon' })
export const MagnifyingGlassIcon = () => React.createElement('div', { 'data-testid': 'magnifying-glass-icon' })
export const FunnelIcon = () => React.createElement('div', { 'data-testid': 'funnel-icon' })
export const ArrowPathIcon = () => React.createElement('div', { 'data-testid': 'arrow-path-icon' })
export const ClockIcon = () => React.createElement('div', { 'data-testid': 'clock-icon' })
export const CurrencyDollarIcon = () => React.createElement('div', { 'data-testid': 'currency-dollar-icon' })
export const UsersIcon = () => React.createElement('div', { 'data-testid': 'users-icon' })
export const BuildingStorefrontIcon = () => React.createElement('div', { 'data-testid': 'building-storefront-icon' })
export const DocumentTextIcon = () => React.createElement('div', { 'data-testid': 'document-text-icon' })
export const BellIcon = () => React.createElement('div', { 'data-testid': 'bell-icon' })
export const Bars3Icon = () => React.createElement('div', { 'data-testid': 'bars-3-icon' })
